name: 'Post to Bluesky'
on:
  schedule:
    - cron: '0 * * * *' # run it on every 1 hour
  workflow_dispatch: {}
jobs:
  postToBluesky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm i -g typescript
      - run: npm i -g ts-node
      - run: npm ci
      - name: tech-blog-rss-feed.bsky.social
        run: npx ts-node src/index.ts
        env: 
          RSS_FEED_URL: https://yamadashy.github.io/tech-blog-rss-feed/feeds/rss.xml
          BLUESKY_USERNAME: tech-blog-rss-feed.bsky.social
          BLUESKY_PASSWORD: ${{ secrets.TECH_BLOG_RSS_FEED_BLUESKY_PASSWORD }}
      - name: logmi-tech.bsky.social
        run: npx ts-node src/index.ts
        env:
          RSS_FEED_URL: https://logmi.jp/feed/public-tech.xml
          BLUESKY_USERNAME: logmi-tech.bsky.social
          BLUESKY_PASSWORD: ${{ secrets.LOGMI_TECH_BLUESKY_PASSWORD }}
